apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodejs-demo
    spec:
      serviceAccount: nodejs-demo-vault
      containers:
        - image: quay.io/spiro-redhat/node.js:latest@sha256:0c5d14e543321a8c40cd4d30df6fe6d76c88e98e261290875565e062e1a712f9
          name: nodejs
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: creds
                  key: token
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits: 
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
              name: web
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
     

     
