apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo-hashi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-demo-hashi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodejs-demo-hashi
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'false'
        vault.hashicorp.com/role: 'my-app'
        vault.hashicorp.com/tls-skip-verify: 'true'
        vault.hashicorp.com/agent-inject-secret-database: 'demo/my-app/dev/database'
        # Environment variable export template
        vault.hashicorp.com/agent-inject-template-database: |
          {{ with secret "demo/my-app/dev/database" -}}
            export USERNAME="{{ .Data.data.username }}"
            export PASSWORD="{{ .Data.data.password }}"
            export TOKEN="Connection string= {{ .Data.data.username }}" 
          {{- end }}
    spec:
      serviceAccount: nodejs-demo-hashi
      containers:
        - image: quay.io/spiro-redhat/node.js:19@sha256:4e7e9ec74254d11389171398c56a11148661c15e497d7599df5faee07ec49cb2
          name: nodejs-demo-hashi
          command: ['/bin/sh', '-c']
          args: ['source /vault/secrets/database && node server.js']
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits: 
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
              name: web
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
     

     
