apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodejs-demo-ss
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodejs-demo-hashi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding-vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: nodejs-demo-hashi
  namespace: nodejs-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-secret
  annotations:
    kubernetes.io/service-account.name: nodejs-demo-hashi
type: kubernetes.io/service-account-token
