apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8200
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: vault-service-endpoint 
# name: vault.hashicorp.local
  labels:
    kubernetes.io/service-name: vault-service
addressType: FQDN
endPoints:
  - addresses:  
    - "spi-hashi-cluster-0-public-vault-fa245183.5d4734c5.z1.hashicorp.cloud" 
ports:
  - name: https
    protocol: TCP
    port: 8200

