apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"openshift-operators-redhat"},"name":"elasticsearch-operator","namespace":"openshift-operators-redhat"},"spec":{"channel":"stable-5.6","installPlanApproval":"Automatic","name":"elasticsearch-operator","source":"redhat-operators","sourceNamespace":"openshift-marketplace"}}
  labels:
    app.kubernetes.io/instance: openshift-operators-redhat
    operators.coreos.com/elasticsearch-operator.openshift-operators-redhat: ""
  name: elasticsearch-operator
  namespace: openshift-operators-redhat
spec:
  channel: stable-5.6
  installPlanApproval: Automatic
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: elasticsearch-operator.v5.6.3
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat 
spec: {}