apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: argo-admins
users:
  - admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: openshift-gitops
data:
  policy.default: role:readonly
  policy.csv: |
    g, system:cluster-admins, role:admin
    g, cluster-admins, role:admin
    g, argo-admins, role:admin 
    p, role:admin, applications, *, */*, allow
  scopes: '[groups]'
   
   