apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: '
pid /tmp/nginx.pid; 
events {}
http {
   server {
      listen 8080;
      location / {
           return 200 "Hello World";
      }
      location ~ \.(html|htm)  {
        root /usr/share/nginx/html;
      }
   }
}
'
