apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: '
pid /tmp/nginx.pid; 
events {
}
http {
   server {
       listen 8080;
      location / {
           default_type "text/html";
           return 200 "Hello world";
       }
   }
}
'