apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: helloworld-app
      containers:
      - image: nginxinc/nginx-unprivileged:latest
        name: nginx
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits: 
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
          name: web
        volumeMounts:
          - name: config-vol
            mountPath: /etc/nginx/
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes:
        - name: config-vol
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
              