apiVersion: v1
data:
  contact.html.ctmpl: e3stIHdpdGggc2VjcmV0ICJhZG1pbi9kZW1vL2RhdGEvbXktYXBwL2Rldi9jb250YWN0IiAtfX0KPGh0bWw+IAo8aGVhZD48L2hlYWQ+Cjxib2R5PgogICAgPGgxPnt7IC5EYXRhLmRhdGEudGl0bGUgfX0gPC9oMT4KICAgIENhbGwgdXMgb24ge3sgLkRhdGEuZGF0YS50ZWxlcGhvbmUgfX0KPC9ib2R5Pgo8L2h0bWw+IAp7ey0gZW5kIC19fQ==
  index.html.ctmpl: e3stIHdpdGggc2VjcmV0ICJhZG1pbi9kZW1vL2RhdGEvbXktYXBwL2Rldi9pbmRleCIgLX19CjxodG1sPiAKPGhlYWQ+PC9oZWFkPgo8Ym9keT4KICAgIDxoMT57eyAuRGF0YS5kYXRhLnRpdGxlIH19IDwvaDE+CiAgICBUaGUgc2VjcmV0IGlzIHt7IC5EYXRhLmRhdGEucGFzc3dvcmQgfX0KPC9ib2R5Pgo8L2h0bWw+IAp7ey0gZW5kIC19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: vault-agent-template-web-pages
