{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "creds",
    "namespace": "nodejs-demo",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "creds",
        "namespace": "nodejs-demo",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "token": "AgAvdqeKG1JJ3nO3hNBdpbczQFE9HRvTfJjU0LZMfek4ChVwy0oIlvq1LF9rYcQHLRJ2jvUFvZtfFQH6T+afvJ5sesza+lhNF46HlpNzjSU+EtUvTXsWEkkYCry077XmwW1goe3OZBB7vRdMuWjoZ2lLb0kONxBKCD9GpB/FA4K6Swn0z6dNxMGUgG0PdFwCOUL3MihortL4fqzXziiBuPYT1LlasSpMqZvCuIXT9lM8QGNTgvqG8ZYINQX3+ofVDhvf4zld9mINQcHwM0LAitXrp3HsUP6ZGFuItxIYKdumLaBdfwhPvp8uIsLjkzNcSXO9JL3o9uxOWmJ5sU5y/hPiQ97mB0LgICl1WX+8wtIe/CbvfPXIp3zFdMVpZ9EsrMsmBKCKj8q4AtmChbIZ5n7Mtt3+7NANIbXjXcf2zEIY4KJb3fxytmnMlAb/JE1hhhJ6ljcFPOIG3Jc1IyzVQe59chFW5ku8FnwrUBG76tSUrlcdy0nDJgn91jbGdCgZiGPGD3RucPauZSCSwLQbG4cnQI9bVIhEeM0YdYgMKWFRCqYQorDyw1/9bri/B/9PYzZNSUrPzw8rK5hoqxYNZ/8qOfcG1zyrGpBAmHhN+qvqq9Osb3u/fHcoYFlb6IaEdwy6p2/9RudW5DTfyl5WOcuhYNfqDfin3jiaM/CPgjvE/Hu25Bp686cTK+nYAKEIW90CAeoKxJu/qfSjLf5hjKr7tJxrFQpv9dVBiZJdrv4lJm+h"
    }
  }
}
