apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: git@github.com:Vodafone/rnd-openshift.git
      revision: HEAD
      directories:
      - path: gitops-config/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:Vodafone/rnd-openshift.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: in-cluster
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
