apiVersion: config.openshift.io/v1
kind: OAuth
namespace: openshift-config
metadata:
  name: cluster
spec:
  identityProviders:
  - name: my-htpasswd-provider
    challenge: true
    login: true
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: my-htpasswd-secret