apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  name: echo
spec:
  params:
    - name: TERM
      type: string
      description: The term to echo
  steps:
    - name: echo
      image: registry.access.redhat.com/ubi9/ubi
      command:
        - echo
      args:
        - $(inputs.params.TERM)