apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  generateName: tutorial-pipelinerun-
spec:
  pipelineRef:
    name: tutorial-pipeline
  params:
    - name: TERM
      value: "Hello world"
  workspaces:
    - name: pipeline-cache
      volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
