apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  name: echo
spec:
  workspaces:
    - name: cache
  params:
    - name: GIT_REF
      type: string
    - name: GIT_REPO_NAME
      type: string
    - name: GIT_REPO_URL
      type: string
    - name: TERM
      type: string
  steps:
    - name: echo
      image: registry.access.redhat.com/ubi9/ubi
      command:
        - echo
      args:
        - $(params.TERM)
    - name: redirect
      image: registry.access.redhat.com/ubi9/ubi
      script: |
         echo $(params.TERM) > $(workspaces.cache.path)/README.md
         echo $(params.GIT_REPO_NAME) >> $(workspaces.cache.path)/README.md
         echo $(params.GIT_REPO_URL) >> $(workspaces.cache.path)/README.md
         echo $(params.GIT_REF) >> $(workspaces.cache.path)/README.md
         cat $(workspaces.cache.path)/README.md
      