apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tutorial-pipeline
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  workspaces:
    - name: pipeline-cache
  tasks:
    - name: echo-something
      taskRef:
        name: echo
      workspaces:
        - name: cache
          workspace: pipeline-cache
      params:
        - name: TERM
          value: "Hello world!"
        - name: GIT_REPO
          value: "PLACE HOLDER"