kind: ServiceAccount 
apiVersion: v1
metadata: 
  name: tekton-github-triggers
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name: tekton-github-triggers
rules: 
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings" , "serviceaccounts"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets" , "serviceaccounts"]
    verbs: ["get" , "list", "watch","patch"]
  - apiGroups: ["tekton.dev"] 
    resources: ["pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["create"]   
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name: tekton-github-triggers
subjects:
  - kind: ServiceAccount
    name: tekton-github-triggers
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-github-triggers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-github-triggers-cluster-role
  namespace: tekton-pipelines
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - clusterinterceptors
      - clustertriggerbindings
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-github-triggers-cluster-role-binding
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-github-triggers-cluster-role
subjects:
  - kind: ServiceAccount
    name: tekton-github-triggers
    namespace: tekton-pipelines


    