apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tutorial-triggertemplate
spec:
  params:
    - name: git-revision 
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
    
  resourcetemplates: 
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun 
      metadata: 
        labels: 
          tekton.dev/pipeline: tutorial-pipeline 
        generateName: tutorial-pipeline-webhook-
      spec:
        pipelineRef: 
          name: tutorial-pipeline
        serviceAccountName: tekton-github-triggers
        params: 
          - name: GIT_REPO_URL
            value: $(tt.params.git-repo-url)
          - name: GIT_REPO_NAME
            value: $(tt.params.git-repo-name)
          - name: GIT_REF
            value: $(tt.params.git-revision) 
          - name: TERM
            value: $(tt.params.pusher-name) 
          - name: COMMIT_MESSAGE
            value: $(tt.params.git-commit-message)
        workspaces: 
          - name: pipeline-cache
            volumeClaimTemplate:
             spec:
                accessModes:
                   - ReadWriteOnce
                resources:
                  requests:
                     storage: 100Mi
---
kind: TriggerBinding
apiVersion: triggers.tekton.dev/v1alpha1 
metadata:
  name: tutorial-triggerbinding 
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.clone_url) 
    - name: git-repo-name
      value: $(body.repository.name)
    - name: git-revision
      value: $(body.head_commit.id)
    - name: pusher-name
      value: $(body.pusher.name)
    - name: git-commit-message
      value: $(body.commits[0].message)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tutorial-eventlistener 
spec:
  serviceAccountName: tekton-github-triggers
  triggers:
    - name: github-trigger
      interceptors:
        - github:
            #secretRef: 
            #  secretName: github-trigger-secret
            #  secretKey: secret-token
            eventTypes:
              - push
        - cel: 
            filter: "body.ref == 'refs/heads/main'"
      bindings:
        - ref:  tutorial-triggerbinding
      template:
        ref: tutorial-triggertemplate