apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: creds
  namespace: sealed-secrets
spec:
  encryptedData:
    token: AgAhhDmI8TsHXK30SYLkqPSGyv//+lOIz87/c2eOe2UbdJArmvKU/qyf7lrDZXhjlb8G8G0w1+4+FMKMVsZgXsHP9J8sawd0p8sWUouQh7UEYL23mMScK0oe7+64OP2KZ/K7VT8NS2BYbJO9+wnmULKmXmWU7aRm3oRPypd+BeQF3F/yiUGjwBWsmfBJC8fhEKtShVGktUFFWFKQNl+rQWrVFaCxvAJjRvqs0Sz+mvJe5SVsxzsqBD4T3mdO1X37evfJ0ADK9XS7Rv9ycA9gmZURFj3jKPYGiUbuXMkttIkB0QIjnbplZI4m4Lz2hNOLDImcyFK7o9hxzMEA7lBPHfhYPG9EkmhTrIsCribLZ06qBh/Gp1072bPR19ZDOH6dX595ic/BHq6CZXMjsJNIdEbSq2C/SnKMpY01bNw+WigBE+fqiOANmhcK6Oru395twVo5qE69rCRIa1ZWX2WRe6uA2amG8oSNaNnrTMs1LZCPHUCX4u0+0/A+0d7c8CT/KfJ1l4VXcDzUObJyyQI4gEeEJdyydEIJYMs5Df9sexLYVkXc2FevHJiNbmp4aKNFydekmeXDsgdiH4DqjkGioWjJVf9tTFd3gSrZ3H9M5tRBdHeeZHLLPKJ6y6aG1mOpOx/AE/xOAjWZungTNW4OtEgHMabDx6IzUZNlUlqjCZA/HWig8DxgyBhH/NzTQbRqTdUqoEVNf4Yl91nphtYd4cOS1qEZDAyQYGiq
  template:
    metadata:
      creationTimestamp: null
      name: creds
      namespace: sealed-secrets
    type: Opaque

