apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  inputs:
    - name: audit
  outputs:
    - name: audit-logs
      secret:
        name: elasticsearch
      syslog:
        rfc: RFC5424
      type: elasticsearch
  pipelines:
    - inputRefs:
        - application
        - audit
        - infrastructure
      name: enable-default-log-store
      outputRefs:
        - default
    - inputRefs:
        - application
      name: forward-to-remote
      outputRefs:
        - remote-elasticsearch
